# Generated by Django 5.2.10 on 2026-01-13 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='会社名')),
                ('business_type', models.CharField(max_length=50, verbose_name='事業形態')),
                ('is_verified', models.BooleanField(default=False, verbose_name='本人確認済み')),
                ('verification_document', models.FileField(blank=True, null=True, upload_to='docs/', verbose_name='確認書類')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100, verbose_name='店舗名')),
                ('post_code', models.CharField(max_length=7, verbose_name='郵便番号')),
                ('prefecture', models.CharField(max_length=20, verbose_name='都道府県')),
                ('city', models.CharField(max_length=100, verbose_name='市区町村名')),
                ('address_line', models.CharField(max_length=100, verbose_name='町域・番地')),
                ('building', models.CharField(blank=True, max_length=100, verbose_name='建物名など')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.businessprofile')),
            ],
        ),
    ]
