# Generated by Django 5.2.10 on 2026-01-14 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='求人タイトル')),
                ('industry', models.CharField(max_length=100, verbose_name='業種')),
                ('occupation', models.CharField(max_length=100, verbose_name='職種')),
                ('work_content', models.TextField(verbose_name='業務内容')),
                ('precautions', models.TextField(verbose_name='注意事項')),
                ('has_unexperienced_welcome', models.BooleanField(default=False)),
                ('has_transportation_allowance', models.BooleanField(default=False)),
                ('has_meal', models.BooleanField(default=False)),
                ('has_hair_color_free', models.BooleanField(default=False)),
                ('belongings', models.TextField(verbose_name='持ち物')),
                ('requirements', models.TextField(verbose_name='働くための条件')),
                ('address', models.CharField(max_length=255, verbose_name='就業場所の住所')),
                ('access', models.TextField(verbose_name='アクセス')),
                ('contact_number', models.CharField(max_length=20, verbose_name='緊急連絡先')),
                ('auto_message', models.TextField(verbose_name='自動送信メッセージ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.store')),
            ],
        ),
    ]
