# Generated by Django 5.2.10 on 2026-01-14 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_jobtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(verbose_name='勤務日')),
                ('start_time', models.TimeField(verbose_name='開始時間')),
                ('end_time', models.TimeField(verbose_name='終了時間')),
                ('title', models.CharField(max_length=200, verbose_name='求人タイトル')),
                ('work_content', models.TextField(verbose_name='業務内容')),
                ('is_published', models.BooleanField(default=False, verbose_name='公開フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.jobtemplate', verbose_name='元にするひな形')),
            ],
        ),
    ]
