# Generated by Django 5.2.10 on 2026-01-15 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_jobposting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='work_content',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='hourly_wage',
            field=models.IntegerField(default=1100, verbose_name='時給'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='transportation_fee',
            field=models.IntegerField(default=500, verbose_name='交通費'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.jobtemplate'),
        ),
    ]
