# Generated by Django 5.2.10 on 2026-01-15 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_remove_jobposting_work_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='work_content',
            field=models.TextField(blank=True, null=True, verbose_name='業務内容'),
        ),
    ]
