# Generated by Django 5.2.10 on 2026-01-21 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtemplate',
            name='has_bicycle_commute',
            field=models.BooleanField(default=False, verbose_name='自転車通勤可'),
        ),
        migrations.AddField(
            model_name='jobtemplate',
            name='has_bike_bicycle_commute',
            field=models.BooleanField(default=False, verbose_name='バイク/自転車通勤可'),
        ),
        migrations.AddField(
            model_name='jobtemplate',
            name='has_bike_car_commute',
            field=models.BooleanField(default=False, verbose_name='バイク/車通勤可'),
        ),
        migrations.AddField(
            model_name='jobtemplate',
            name='has_clothing_free',
            field=models.BooleanField(default=False, verbose_name='服装自由'),
        ),
        migrations.AddField(
            model_name='jobtemplate',
            name='has_coupon_get',
            field=models.BooleanField(default=False, verbose_name='クーポンGET'),
        ),
        migrations.AddField(
            model_name='jobtemplate',
            name='has_smoking_area',
            field=models.BooleanField(default=False, verbose_name='喫煙可能エリアでの作業あり'),
        ),
        migrations.AddField(
            model_name='jobtemplate',
            name='manual_pdf',
            field=models.FileField(blank=True, null=True, upload_to='job_manuals/', verbose_name='業務に関する書類(PDF)'),
        ),
        migrations.AddField(
            model_name='jobtemplate',
            name='smoking_prevention',
            field=models.CharField(choices=[('indoor_no_smoking', '屋内禁煙'), ('indoor_smoking_separate', '分煙'), ('indoor_smoking_ok', '屋内喫煙可')], default='indoor_no_smoking', max_length=50, verbose_name='受動喫煙防止措置'),
        ),
        migrations.AlterField(
            model_name='jobtemplate',
            name='access',
            field=models.TextField(blank=True, null=True, verbose_name='アクセス'),
        ),
        migrations.AlterField(
            model_name='jobtemplate',
            name='auto_message',
            field=models.TextField(blank=True, null=True, verbose_name='自動送信メッセージ'),
        ),
        migrations.AlterField(
            model_name='jobtemplate',
            name='belongings',
            field=models.TextField(blank=True, null=True, verbose_name='持ち物'),
        ),
        migrations.AlterField(
            model_name='jobtemplate',
            name='has_hair_color_free',
            field=models.BooleanField(default=False, verbose_name='髪型/カラー自由'),
        ),
        migrations.AlterField(
            model_name='jobtemplate',
            name='has_meal',
            field=models.BooleanField(default=False, verbose_name='まかないあり'),
        ),
        migrations.AlterField(
            model_name='jobtemplate',
            name='has_transportation_allowance',
            field=models.BooleanField(default=False, verbose_name='交通費支給'),
        ),
        migrations.AlterField(
            model_name='jobtemplate',
            name='has_unexperienced_welcome',
            field=models.BooleanField(default=False, verbose_name='未経験者歓迎'),
        ),
        migrations.AlterField(
            model_name='jobtemplate',
            name='requirements',
            field=models.TextField(blank=True, null=True, verbose_name='働くための条件'),
        ),
        migrations.CreateModel(
            name='JobTemplatePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='job_templates/photos/', verbose_name='写真')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='business.jobtemplate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
