# Generated by Django 5.2.10 on 2026-01-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_jobtemplate_has_bicycle_commute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtemplate',
            name='qualification_type',
            field=models.CharField(blank=True, choices=[('none', '選択してください'), ('ordinary_car_license', '普通自動車免許'), ('moped_license', '原付免許'), ('forklift', 'フォークリフト'), ('food_hygiene_manager', '食品衛生責任者'), ('cook', '調理師')], default='none', max_length=50, null=True, verbose_name='資格種別'),
        ),
        migrations.AddField(
            model_name='jobtemplate',
            name='requires_qualification',
            field=models.BooleanField(default=False, verbose_name='資格が必要ですか？'),
        ),
    ]
