# Generated by Django 5.2.10 on 2026-01-22 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_jobtemplate_qualification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtemplate',
            name='qualification_type',
            field=models.CharField(blank=True, choices=[('none', '選択してください'), ('ordinary_car_license', '普通自動車免許'), ('mid_size_car_license', '中型自動車免許'), ('large_size_car_license', '大型自動車免許'), ('semi_mid_size_car_license', '準中型自動車免許'), ('motorcycle_license', '普通自動二輪車免許'), ('large_motorcycle_license', '大型自動二輪車免許'), ('moped_license', '原付免許'), ('forklift', 'フォークリフト'), ('hazardous_materials_b4', '危険物取扱者（乙4）'), ('food_hygiene_manager', '食品衛生責任者'), ('cook', '調理師'), ('nursing_care_basics', '介護職員初任者研修'), ('registered_seller', '登録販売者'), ('security_guard_training', '警備員新任教育受講済'), ('health_supervisor', '衛生管理者')], default='none', max_length=50, null=True, verbose_name='資格種別'),
        ),
    ]
