# Generated by Django 5.2.10 on 2026-01-22 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_alter_jobtemplate_qualification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtemplate',
            name='qualification_notes',
            field=models.TextField(blank=True, null=True, verbose_name='資格の補足情報'),
        ),
    ]
