# Generated by Django 5.2.10 on 2026-01-22 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_jobtemplate_qualification_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualificationMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='資格名称')),
                ('category', models.CharField(max_length=100, verbose_name='カテゴリ')),
            ],
        ),
        migrations.AlterField(
            model_name='jobtemplate',
            name='qualification_type',
            field=models.CharField(blank=True, choices=[('none', '選択してください'), ('ordinary_car_license', '普通自動車免許'), ('mid_size_car_license', '中型自動車免許'), ('large_size_car_license', '大型自動車免許'), ('semi_mid_size_car_license', '準中型自動車免許'), ('motorcycle_license', '普通自動二輪車免許'), ('large_motorcycle_license', '大型自動二輪車免許'), ('moped_license', '原付免許'), ('forklift', 'フォークリフト'), ('hazardous_materials_b4', '危険物取扱者（乙4）'), ('food_hygiene_manager', '食品衛生責任者'), ('cook', '調理師'), ('nursing_care_basics', '介護職員初任者研修'), ('registered_seller', '登録販売者'), ('security_guard_training', '警備員新任教育受講済'), ('health_supervisor', '衛生管理者')], default='none', max_length=50, null=True, verbose_name='資格種別(旧)'),
        ),
        migrations.AddField(
            model_name='jobtemplate',
            name='qualification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.qualificationmaster', verbose_name='必須資格'),
        ),
    ]
