# Generated by Django 5.2.10 on 2026-01-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_qualificationmaster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='break_duration',
            field=models.IntegerField(default=0, verbose_name='休憩時間(分)'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='break_start',
            field=models.TimeField(blank=True, null=True, verbose_name='休憩開始時間'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='recruitment_count',
            field=models.IntegerField(default=1, verbose_name='募集人数'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='visibility',
            field=models.CharField(choices=[('public', '一般公開'), ('badge', 'バッジ限定'), ('group', 'グループ限定')], default='public', max_length=20, verbose_name='公開範囲'),
        ),
    ]
