# Generated by Django 5.2.10 on 2026-01-23 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_badge_workerbadge'),
        ('business', '0012_jobposting_break_duration_jobposting_break_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreWorkerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_type', models.CharField(choices=[('favorite', 'お気に入り'), ('worked', '稼働経験あり'), ('blocked', 'ブロック'), ('hall', 'ホール')], max_length=50, verbose_name='グループ種別')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.store')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.workerprofile')),
            ],
            options={
                'unique_together': {('store', 'worker', 'group_type')},
            },
        ),
        migrations.CreateModel(
            name='StoreWorkerMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.TextField(blank=True, verbose_name='管理用メモ')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.store')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.workerprofile')),
            ],
            options={
                'unique_together': {('store', 'worker')},
            },
        ),
    ]
