# Generated by Django 5.2.10 on 2026-01-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_storeworkergroup_storeworkermemo'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtemplate',
            name='other_conditions',
            field=models.TextField(blank=True, null=True, verbose_name='その他の条件'),
        ),
        migrations.AddField(
            model_name='jobtemplate',
            name='skills',
            field=models.TextField(blank=True, null=True, verbose_name='必要なスキル'),
        ),
    ]
