# Generated by Django 5.2.10 on 2026-01-24 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_jobtemplate_other_conditions_jobtemplate_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='address_line',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='町域・番地'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='building',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='建物名など'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='市区町村名'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='post_code',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='郵便番号'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='prefecture',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='都道府県'),
        ),
    ]
