# Generated by Django 5.2.10 on 2026-01-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_businessprofile_address_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='industry',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='業種'),
        ),
    ]
