# Generated by Django 5.2.10 on 2026-01-24 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_businessprofile_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='industry',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='業種'),
        ),
    ]
