# Generated by Django 5.2.10 on 2026-01-26 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0017_store_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='application_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='応募締切日時'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='visibility',
            field=models.CharField(choices=[('public', '一般公開'), ('badge', 'バッジ限定'), ('group', 'グループ限定'), ('first_time', '初回ワーカー限定'), ('url', 'URL限定')], default='public', max_length=20, verbose_name='公開範囲'),
        ),
    ]
