# Generated by Django 5.2.10 on 2026-01-27 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_jobposting_application_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='is_long_term',
            field=models.BooleanField(default=False, verbose_name='長期バイト募集'),
        ),
    ]
