# Generated by Django 5.2.10 on 2026-01-29 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0020_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='attendance_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='出勤日時'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='leaving_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='退勤日時'),
        ),
    ]
