# Generated by Django 5.2.10 on 2026-01-29 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0021_jobapplication_attendance_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='緯度'),
        ),
        migrations.AddField(
            model_name='store',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='経度'),
        ),
    ]
