# Generated by Django 5.2.10 on 2026-01-29 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0023_remove_message_application_chatroom_message_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correction_attendance_at', models.DateTimeField(verbose_name='修正出勤日時')),
                ('correction_leaving_at', models.DateTimeField(verbose_name='修正退勤日時')),
                ('correction_break_time', models.IntegerField(default=0, verbose_name='修正休憩時間(分)')),
                ('lateness_reason', models.CharField(blank=True, choices=[('workplace', '働き先の都合'), ('personal', 'ご自身の都合'), ('disaster', '自然災害・交通遅延など'), ('other', 'その他')], max_length=20, null=True, verbose_name='遅刻理由')),
                ('lateness_reason_detail', models.TextField(blank=True, null=True, verbose_name='遅刻理由詳細')),
                ('status', models.CharField(choices=[('pending', '申請中'), ('approved', '承認済み'), ('rejected', '却下')], default='pending', max_length=20, verbose_name='ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='business.jobapplication')),
            ],
        ),
    ]
