# Generated by Django 5.2.10 on 2026-01-29 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_workerprofile_identity_document1'),
        ('business', '0024_attendancecorrection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeworkergroup',
            name='group_type',
            field=models.CharField(blank=True, choices=[('favorite', 'お気に入り'), ('worked', '稼働経験あり'), ('blocked', 'ブロック'), ('hall', 'ホール')], max_length=50, null=True, verbose_name='グループ種別'),
        ),
        migrations.CreateModel(
            name='StoreGroupDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='グループ名')),
                ('is_shared', models.BooleanField(default=False, verbose_name='企業内共有')),
                ('is_system', models.BooleanField(default=False, verbose_name='システム予約')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_definitions', to='business.store')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='storeworkergroup',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='storeworkergroup',
            name='group_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_groups', to='business.storegroupdefinition'),
        ),
        migrations.AlterUniqueTogether(
            name='storeworkergroup',
            unique_together={('store', 'worker', 'group_type', 'group_definition')},
        ),
        migrations.CreateModel(
            name='WorkerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('good', 'Good'), ('bad', 'Bad')], max_length=10, verbose_name='評価')),
                ('skills', models.JSONField(blank=True, default=list, verbose_name='評価スキル')),
                ('message', models.TextField(blank=True, verbose_name='感謝の言葉')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_review', to='business.jobapplication')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.store')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
