# Generated by Django 5.2.10 on 2026-02-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0025_alter_storeworkergroup_group_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtemplate',
            name='question1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='働く前の質問1'),
        ),
        migrations.AddField(
            model_name='jobtemplate',
            name='question2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='働く前の質問2'),
        ),
        migrations.AddField(
            model_name='jobtemplate',
            name='question3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='働く前の質問3'),
        ),
    ]
