# Generated by Django 5.2.10 on 2026-02-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0026_jobtemplate_question1_jobtemplate_question2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='answer1',
            field=models.TextField(blank=True, null=True, verbose_name='回答1'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='answer2',
            field=models.TextField(blank=True, null=True, verbose_name='回答2'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='answer3',
            field=models.TextField(blank=True, null=True, verbose_name='回答3'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='answered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='回答日時'),
        ),
    ]
