# Generated by Django 5.2.10 on 2026-02-01 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0027_jobapplication_answer1_jobapplication_answer2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_time_matched', models.BooleanField(default=True, verbose_name='働いた時間は求人内容どおりでしたか？')),
                ('is_content_matched', models.BooleanField(default=True, verbose_name='掲載されていた仕事内容通りでしたか？')),
                ('is_want_to_work_again', models.BooleanField(default=True, verbose_name='またここで働きたいですか？')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store_review', to='business.jobapplication')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to='business.store')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_store_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
