# Generated by Django 5.2.10 on 2026-02-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0028_storereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtemplate',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='緯度'),
        ),
        migrations.AddField(
            model_name='jobtemplate',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='経度'),
        ),
    ]
