# Generated by Django 5.2.10 on 2026-02-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0029_jobtemplate_latitude_jobtemplate_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_reward_paid',
            field=models.BooleanField(default=False, verbose_name='報酬支払い済み'),
        ),
    ]
