# Generated by Django 5.2.10 on 2026-02-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0030_jobapplication_is_reward_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='actual_break_duration',
            field=models.IntegerField(default=0, verbose_name='実績休憩時間(分)'),
        ),
    ]
