# Generated by Django 5.2.10 on 2026-02-03 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_workerprofile_emergency_phone_and_more'),
        ('business', '0031_jobapplication_actual_break_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreMute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muted_by_workers', to='business.store')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muted_stores', to='accounts.workerprofile')),
            ],
            options={
                'unique_together': {('worker', 'store')},
            },
        ),
    ]
