# Generated by Django 5.2.10 on 2026-02-03 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0032_storemute'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancecorrection',
            name='reject_reason',
            field=models.TextField(blank=True, help_text='修正依頼の拒否理由', null=True),
        ),
    ]
