# Generated by Django 5.2.10 on 2026-02-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0033_attendancecorrection_reject_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='電話番号'),
        ),
    ]
