# Generated by Django 5.2.10 on 2026-02-05 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_workermembership_grade_notification'),
        ('business', '0034_businessprofile_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualLimitReleaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '申請中'), ('approved', '承認済み'), ('rejected', '却下')], default='pending', max_length=20, verbose_name='ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limit_release_requests', to='business.store')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limit_release_requests', to='accounts.workerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
