@startuml お気に入りの店舗を閲覧する

' 1
actor ワーカー as wo1
boundary お気に入り画面 as fv1
control 表示 as co1
control 表示 as co2

entity お気に入り店舗 as fa1

' 2
fv1 <- co1 :画面を表示する
wo1 -> fv1 :「店舗」ボタンを押下する
fv1 -> co2 :起動()

co2 -> fa1 : お気に入り店舗を参照する()
co2 <-- fa1
alt お気に入り店舗がない場合
    co2 -> fv1 : システムは「仕事をお気に入りしてみましょう」と表示し、\n「仕事をさがす」ボタンを表示する

else ログインしてお気に入りがある場合
    co2 -> fv1 : お気に入りを表示する

end

@enduml