@startuml お気に入り求人の絞り込みをする

' 1
actor ワーカー as wo1
boundary お気に入り画面 as fv1
control 表示 as co1

control 処理 as co2

entity お気に入り as fa1

' 2
co1 -> fa1 : お気に入り求人を参照する
co1 <-- fa1
co1 -> fv1 : 画面を表示する

alt ログインしていない場合
    co1 -> fv1 : システムは「ログインが必要です」と表示し、\n「登録する」ボタンを表示する　    

    alt ログインしている場合
        co1 -> fv1 : システムは「仕事をお気に入りしてみましょう」と\n画面に表示し、「仕事をさがす」ボタンを表示する

    else お気に入り求人がある場合
        co1 -> fv1 : システムはお気に入り求人を表示する
        wo1 -> fv1 : ユーザーは\n「募集中の仕事のみを表示」ボタンを押下する
        fv1 -> co2 : 起動method_POST()
        co2 -> fa1 : お気に入り求人の「募集中の仕事のみ」を参照する
        co2 <-- fa1
        co2 -> fv1 : システムは募集中の仕事のみを表示する

    end

end

@enduml