@startuml お気に入り求人の絞り込みをする

' 1
actor ワーカー as wo1
boundary お気に入り画面 as fv1
control 表示 as co1

entity お気に入り as fa1

' 2
co1 -> fv1 : システムは画面を表示する
wo1 -> fv1 : ユーザーは\n「募集中の仕事のみを表示」ボタンを押下する

alt お気に入り店舗がない場合
    fv1 -> fv1 : システムは「仕事をお気に入りしてみましょう」と\n画面に表示し、「仕事をさがす」ボタンを表示する

else お気に入り店舗がある場合
    fv1 -> fa1 : お気に入りを参照して\n募集中の仕事のみを表示する
    fv1 <-- fa1

    fv1 -> fv1 : システムは画面を表示する

end

@enduml