@startuml お仕事をキャンセルする

actor ワーカー as wo1
boundary はたらく画面 as wk1
control 表示 as co1

boundary 仕事詳細画面 as jsd1
boundary キャンセル確認画面 as cnf1
boundary キャンセル理由選択画面 as crs1
boundary キャンセル理由入力画面 as cri1
boundary キャンセル理由入力内容確認画面 as cfc1
boundary キャンセル内容最終確認画面 as cfc2
boundary キャンセル完了画面 as cmp1
entity 予定 as en1

co1 -> en1 : 予定を参照する
en1 --> co1
alt 応募済みのお仕事がない場合
    co1 -> wk1 : 「今後の予定はありません」「次のお仕事を探してみましょう」と「仕事を探す」ボタンを表示する
else 応募済みのお仕事がある場合
    co1 -> wk1 : 表示する
    wo1 -> wk1 : 応募が確定したお仕事を選択する
    wk1 -> jsd1 :表示する
    wo1 -> jsd1 : 「このお仕事をキャンセル」ボタンを押下する
    jsd1 -> cnf1 : 表示する
    wo1 -> cnf1 : 「キャンセルにすすむ」ボタンを押下する
    cnf1 -> crs1 : 表示する
    wo1 -> crs1 : キャンセル理由を選択した場合「メッセージを入力」ボタンを押下する
    crs1 -> cri1 : 表示する
    wo1 -> cri1 : キャンセルの理由を入力し、「次へ」ボタンを押下する
    cri1 -> cfc1 : 表示する
    wo1 -> cfc1 : 入力内容を確認し「次へ」ボタンを押下する
    cfc1 -> cfc2 : 表示する
    wo1 -> cfc2 : 「キャンセルを完了」ボタンを押下する
    cfc2 -> cfc2 : ポップを表示する
    wo1 -> cfc2 : ボタンを押下する
    alt 「キャンセル」ボタンを押下した場合
        cfc2 -> cfc2 : ポップを隠し、表示する
    else 「確定する」ボタンを押下した場合
        cfc2 -> cfc2 :「キャンセルしました」のポップを表示する
        wo1 -> cfc2 : 「OK」ボタンを押下する
        cfc2 -> en1 : 削除する
        cfc2 <-- en1
        cfc2 -> wk1 : 表示する
    end 
end 





@enduml
