@startuml クラス図

skinparam classAttributeIconSize 0

class ワーカー {
    - 電話番号:int
    - パスワード:String
    - 氏名:String
    - プロフィール写真:PATH
    - 生年月日:Date
    - 住所:String
    - 緊急連絡先:int
    - 働き方:String
    - 所属:String
    ' 資格
    ' 実績
    ' バッチ
    ' ペナルティ
    ' ワーカー側メッセージ
    ' 店舗からのレビュー
    ' 店舗からの評価
    ' ミュートしている店舗
    ' 銀行口座
    - ウォレット残高:int
    ' 獲得報酬

    ' お気に入り店舗
    ' お気に入り求人
    ' 今後の予定
    ' これまでの仕事

    + ワーカーを参照する():object
    + プロフィール写真を変更する():void
    + 緊急連絡先を変更する():void
    + 働き方を変更する():void
    + 所属を変更する():void
    + ウォレット残高を変更する():void
}

class 資格 {
    - ワーカー:FK
    - 資格種別:String
    - 資格:PATH

    + 資格種別を参照する():String
    + 資格を登録する(object):void
}

class 実績 {
    - ワーカー:FK
    - 働いた時間:int
    - 働いた回数:int
    - good数:int

    + 実績を追加する():object
    + 実績を参照する():object
}

class 取得済みバッチ {
    - ワーカー:FK
    - バッチ:FK
    
}

'
class バッチ {
    - バッチ名:String
    - 業務内容:String
    - 働いた回数:int
    - 求人:FK
    - 対応職種:String

    + バッチを登録する(object):void
    + バッチを参照する():object
}
'

class ペナルティ {
    - ワーカー:FK
    - ペナルティ:String
    - ペナルティポイント:int
    - キャンセル数:int
    - 直前キャンセル数:int

    + ペナルティを変更する():void
    + ペナルティポイントを変更する():void
    + キャンセル数を変更する():void
    + 直前キャンセル数を変更する():void
    + ペナルティを参照する():object
}

class 店舗からのレビュー {
    - ワーカー:FK
    - 店舗:FK
    - レビュー:String

    + レビューを登録する(object):void
    + レビューを参照する():object
}

' class 店舗からの評価 {
'    good数
'    bad数
'}

class ミュートしている店舗 {
    - ワーカー:FK
    - 店舗:FK
}

class 銀行口座{
    - ワーカー:FK
    - 銀行名:String
    - 口座種別:String
    - 支店名:String
    - 口座番号:int
    - 口座名義:String

    + 銀行口座を変更する():object
    + 銀行口座を参照する():object
    + 銀行口座を追加する(object):void
}

'class 獲得報酬 {
'    - ワーカー:FK
'}

class 店舗ごとの報酬 {
    - ワーカー:FK
    - 店舗:FK
    - 月報酬:int
    - 年報酬:int

    + 店舗ごとの報酬を変更する():object
    + 店舗ごとの報酬を参照する():object
    + 店舗ごとの報酬を登録する(object):void
}

class お気に入り店舗 {
    - ワーカー:FK
    - 店舗:FK
}

class お気に入り求人 {
    - ワーカー:FK
    - 求人:FK
}

class 今後の予定 {
    - ワーカー:FK
    - 求人:FK
}

class これまでの仕事 {
    - ワーカー:FK
    - 求人:FK
    - 修正依頼:FK
    - 業務開始時間:int
    - 業務終了時間:int
    - 休憩時間:int

    + これまでの仕事を参照する():object
    + これまでの仕事を登録する(object):void
}

class 給与明細 {
    - これまでの仕事:FK
    - 時給:int
    - 基本給:int
    - 法廷時間外割増手当:int
    - 深夜割増手当:int
    - 源泉徴収額:int
    - 交通費:int
    - 差し引き支給額:int
    - 交通費:int
    - 差引支給額:int

    + 給与明細を参照する():object
    + 給与明細を登録する(object):void
}

class 店舗 {
    - 企業:FK
    - 店舗ID（QR用）:PK
    - 店名:String
    - 業務内容:String
    ' 求人のひな型
    ' ブロックしているワーカー
    - ワーカーからのレビュー:FK
    - 電話番号:int

    + 店舗を参照する():object
    + 店名を変更する():void
    + 電話番号を変更する():void
    + QRコードを生成する():PATH
}

class 求人 {
    - 店舗:FK
    - 求人ひな型:FK
    - 求人タイトル:String
    - 日付:Date
    - 職種:String
    - 募集締め切り:Date
    - 募集人数:int
    - 報酬:int
    - 待遇:String
    - 働くための条件:String
    - 交通費:int
    - 時給:int
    - 店舗情報:String
    - 契約形態:String
    - 企業:FK

    + 求人を参照する():object
    + 求人を登録する(object):void
}

class 求人のひな型 {
    - 店舗:FK
    - 業務内容:String
    - 注意事項:String
    - 持ち物:String
    - 働く前の質問:String
    - 求人ヘッダー:PATH
    - 住所:String
    - マップ:String
    - アクセス:String
    - 緊急連絡先:int
    - 自動送信メッセージ:String
    - 資格設定:String

    + 求人のひな型を参照する():object
    + 求人のひな型を登録する(object):void
}

class ブロックしているワーカー {
    - 店舗:FK
    - ワーカー:FK
}

class 企業 {
    - メールアドレス:String
    - パスワード:String
    - 企業名:String
    - 業種:String
    - 業務内容:String
    - 住所:String
    - 書類:FK
    - 事業形態:String
    

    + 企業を参照する():object
}

class 書類 {
    - 書類:PATH
    - 企業:FK
}

class メッセージ {
    - ワーカー:FK
    - 店舗:FK
    - メッセージ:String

    + メッセージを参照する():String
    + メッセージを登録する(String):void
}

class ワーカーからのレビュー {
    - ワーカー:FK
    - 店舗:FK
    - 項目:String
    - good数:int
    - bad数:int
    - レビュー

    + ワーカーからのレビューを参照する():object
    + ワーカーからのレビューを登録する(object):void
}

class メール {
    - メールアドレス:String

    + メールアドレスを参照する():String
    + メールアドレスを登録する(String):void
    + メールを送信する():void
}

class 修正依頼 {
    - これまでの仕事:FK
    - 業務開始時間:int
    - 業務終了時間:int
    - 休憩時間:int
    - 修正依頼理由:String

    + 修正依頼を参照する():object
    + 修正依頼を登録する(object):void
}



ワーカー "1" -- "0..*" 資格
ワーカー "1" -- "0..*" 実績
ワーカー "1" -- "0..*" 取得済みバッチ
ワーカー "1" -- "0..*" ペナルティ
ワーカー "1" -- "0..*" メッセージ
ワーカー "1" -- "0..*" 店舗からのレビュー
ワーカー "1" -- "0..*" ミュートしている店舗
ワーカー "1" -- "0..1" 銀行口座
ワーカー "1" -- "0..*" 店舗ごとの報酬
ワーカー "1" -- "0..*" お気に入り求人
ワーカー "1" -- "0..*" お気に入り店舗
ワーカー "1" -- "0..*" 今後の予定
ワーカー "1" -- "0..*" これまでの仕事

お気に入り求人 "0..*" -- "0..*" 求人
お気に入り店舗 "0..*" -- "0..*" 店舗
これまでの仕事 "0..*" -- "0..*" 求人
これまでの仕事 "1" -- "1" 給与明細
今後の予定 "0..*" -- "0..*" 求人

求人 "0..*" -- "1" 店舗
求人 "0..*" -- "1" 企業
店舗ごとの報酬 "0..*" -- "1" 店舗
ミュートしている店舗 "0..*" -- "1" 店舗
店舗からのレビュー "0..*" -- "1" 店舗
店舗 "1" -- "0..*" メッセージ
店舗 "1" -- "0..*" ブロックしているワーカー
店舗 "1" -- "0..*" 求人のひな型
店舗 "1..*" -- "1" 企業

ブロックしているワーカー "0..*" -- "0..*" ワーカー
ワーカーからのレビュー "0..*" -- "1" 店舗
ワーカーからのレビュー "0..*" -- "1" ワーカー

'
取得済みバッチ "0...*" -- "1" バッチ
バッチ "1" -- "0..*" 求人
これまでの仕事 "1" -- "0..1" 修正依頼
求人のひな型 "1" -- "0..*" 求人
'

メール "1" -- "0..*" 企業
書類 "0..*" - "1*" 企業

@enduml