@startuml クラス図

skinparam classAttributeIconSize 0

class ワーカー {
    電話番号
    パスワード
    氏名
    プロフィール写真
    生年月日
    住所
    緊急連絡先
    働き方
    所属
    ' 資格
    実績:FK
    ' バッチ
    ペナルティ
    ワーカー側メッセージ
    レビュー
    店舗からの評価
    ミュートしている店舗
    銀行口座
    ウォレット残高
    獲得報酬

    お気に入り店舗
    お気に入り求人
    今後の予定
    これまでの仕事
}

class 資格 {
    ワーカー:FK
    資格種別
    資格
}

class 実績 {
    働いた時間
    働いた回数
    good率
}

class バッチ {
    ワーカー:FK
    ????????????????????????????????????????????
}

class ペナルティ {
    ペナルティ
    ペナルティポイント
    キャンセル数
    直前キャンセル数
}

class ワーカー側メッセージ {
    店舗
    メッセージ
}

class ワーカー側レビュー {
    店舗
    レビュー
}

class 店舗からの評価 {
    good数
    bad数
}

class ミュートしている店舗 {
    店舗
}

class 銀行口座{
    銀行名
    口座種別
    支店名
    口座番号
    口座名義
}

class 獲得報酬 {
    店舗ごとの報酬
}

class 店舗ごとの報酬 {
    店舗
    月報酬
    年報酬
}

class お気に入り店舗 {
    店舗
}

class お気に入り求人 {
    求人
}

class 今後の予定 {
    求人
}

class これまでの仕事 {
    求人
    業務開始時間
    業務終了時間
    休憩時間
    給与明細番号
}

class 給与明細 {
    給与明細番号
    時給
    基本給
    法廷時間外割増手当
    深夜割増手当
    源泉徴収額
    交通費
    差し引き支給額
    交通費
    差引支給額
}

class 店舗 {
    店名
    業務内容
    店舗側メッセージ
    QRコード
    求人のひな型
    ブロックしているワーカー
    レビュー
    店舗の評価
}

class 店舗側メッセージ {
    ワーカー
    メッセージ
}

class 求人 {
    求人ひな型
    求人タイトル
    職種
    募集締め切り
    募集人数
    報酬
    待遇
    働くための条件
    獲得できる可能性のあるバッチ
    交通費
    時給
    マップ
    店舗情報
    業務に関する書類
    契約形態
    働いた企業
    支払者
}

class 求人のひな型 {
    業務内容
    注意事項
    持ち物
    働く前の質問
    求人ヘッダー
    住所
    マップ
    アクセス
    緊急連絡先
    自動送信メッセージ
    資格設定
}

class ブロックしているワーカー {
    ワーカー
}

class 企業 {
    メールアドレス
    パスワード
    企業名
    業種
    業務内容
    住所
    書類
    事業形態
}

ワーカー "1" -- "0..*" 資格
ワーカー "1" -- "1" 実績
ワーカー "1" -- "0..*"バッチ
ワーカー -- ペナルティ
ワーカー -- ワーカー側メッセージ
ワーカー -- ワーカー側レビュー
ワーカー -- 店舗からの評価
ワーカー -- ミュートしている店舗
ワーカー -- 銀行口座
ワーカー -- 獲得報酬
ワーカー -- お気に入り求人
ワーカー -- お気に入り店舗
ワーカー -- 今後の予定
ワーカー -- これまでの仕事

お気に入り求人 -- 求人
お気に入り店舗 -- 店舗
これまでの仕事 -- 求人
獲得報酬 -- 店舗ごとの報酬
これまでの仕事 -- 給与明細
今後の予定 -- 求人

求人 -- 店舗
店舗ごとの報酬 -- 店舗
ミュートしている店舗 -- 店舗
ワーカー側レビュー -- 店舗
ワーカー側メッセージ -- 店舗
店舗 -- ブロックしているワーカー
店舗 -- 求人のひな型
店舗 -- 企業
店舗 -- 店舗側メッセージ

店舗側メッセージ -- ワーカー
ブロックしているワーカー -- ワーカー


@enduml