@startuml 求人の詳細を閲覧する

' 1
actor ワーカー as wo1
boundary さがす画面 as sc1
control 表示 as co1

boundary 求人詳細画面 as jo1
control 処理 as co2

entity 求人 as en1

' 2
co1 -> en1 : 求人を参照する()
en1 --> co1
co1 -> sc1 : 求人を表示する
wo1 -> sc1 : 求人を押下する
sc1 -> co2 : 起動()
co2 -> en1 : 求人の詳細を参照する()
en1 --> co2
co2 -> jo1 : 求人の詳細を閲覧する


@enduml