@startuml ワーカーのアカウントを作成する

' 1
actor ワーカー as wo1

boundary ログイン画面 as log1
control 表示 as co1
boundary ワーカーアカウント作成画面 as wav1
control 処理 as co2

boundary 氏名記入画面 as nmf1
control 処理 as co3

boundary フリガナ記入画面 as fgf1
control 処理 as co4

boundary 性別選択画面 as gef1
control 処理 as co5

boundary プロフィール画像登録画面 as pp1
control 処理 as co6

boundary 住所登録画面 as adf1 
control 処理 as co7

boundary 所属選択画面 as alf1
control 処理 as co8

boundary 働き方選択画面 as wwf1
control 処理 as co9

boundary 都道府県選択画面 as pff1
control 処理 as co10

boundary 通知と位置情報設定画面 as ncs1
control 処理 as co11

boundary さがす画面 as sc1
entity ワーカーアカウント as ac1

' 2
co1 -> log1 : システムは\n画面を表示する
wo1 -> log1 : アカウント作成ボタン\nを押下する
log1 -> wav1 : ワーカーアカウント作成画面に移動する

wo1 -> wav1 : ユーザーはIDとパスワードを入力し\n「次へ」ボタンを押下する
wav1 -> co2 : 起動()

alt IDが未入力の場合
    co2 -> wav1 : システムは\n「IDを入力してください」\nと表示する

else パスワードが未入力の場合
    co2 -> wav1 : システムは\n「パスワードを入力してください」\nと表示する

else IDが重複している場合
    co2 -> ac1 : 参照する()
    co2 <-- ac1
    co2 -> wav1 : システムは「このIDは使えません」\nと表示する

else IDとパスワードが入力された場合
    co2 -> ac1 : IDとパスワードを登録する
    co2 <-- ac1
    co2 -> nmf1 : システムは\n氏名記入画面に移動する

end

' 3
wo1 -> nmf1 : ユーザーは氏名を入力し\n「次へ」ボタンを押下する
nmf1 -> co3 : 起動()

alt 氏名が未入力の場合
    co3 -> nmf1 : システムは\n「次へ」ボタンが押下できない

else 途中で操作をやめた場合
    co3 -> ac1 : 入力された内容までを保存する
    co3 <-- ac1

else 氏名が入力された場合
    co3 -> ac1 : 氏名を登録する
    co3 <-- ac1
    co3 -> fgf1 : システムは\nフリガナ記入画面に移動する

end

' 4
wo1 -> fgf1 : ユーザーは性別を選択して\n「次へ」ボタンを押下する
fgf1 -> co4 : 起動()

alt フリガナが未入力の場合
    co4 -> fgf1 : システムは\n「次へ」ボタンが押下できない

else 途中で操作をやめた場合
    co4 -> ac1 : 入力された内容までを保存する
    co4 <-- ac1

else フリガナが入力された場合
    co4 -> ac1 : フリガナを登録する
    co4 <-- ac1
    co4 -> gef1 : システムは\n性別選択画面へ移動する

end

' 5
wo1 -> gef1 : ユーザーは性別を選択して\n「次へ」ボタンを押下する
gef1 -> co5 : 起動()

alt 性別が未選択の場合
    co5 -> gef1 : システムは\n「次へ」ボタンが押下できない

else 途中で操作をやめた場合
    co5 -> ac1 : 入力された内容までを保存する
    co5 <-- ac1

else 性別を選択した場合
    co5 -> ac1 : 性別を登録する
    co5 <-- ac1
    co5 -> pp1 : システムは\nプロフィール画像登録画面に移動する

end

' 6
wo1 -> pp1 : ユーザーはプロフィール画像を登録し\n「次へ」ボタンを押下する
pp1 -> co6 : 起動()

alt 途中で操作をやめた場合
    co6 -> ac1 : 入力された内容までを保存する
    co6 <-- ac1

else プロフィール画像を登録した場合
    co6 -> ac1 : プロフィール画像を登録する
    co6 <-- ac1
    co6 -> adf1 : システムは\n住所登録画面へ移動する

end

' 7
wo1 -> adf1 : ユーザーは住所を入力し\n「次へ」ボタンを押下する
adf1 -> co7 : 起動()

alt 住所が未入力の場合
    co7 -> adf1 : システムは\n「次へ」ボタンが押下できない

else 途中で操作をやめた場合
    co7 -> ac1 : 入力された内容までを保存する
    co7 <-- ac1

else 住所が入力された場合
    co7 -> ac1 : 住所を登録する
    co7 <-- ac1
    co7 -> alf1 : 所属選択画面に移動する

end

' 8
wo1 -> alf1 : ユーザーは所属選択をして\n「次へ」ボタンを押下する
alf1 -> co8 : 起動()

alt 所属が未選択の場合
    co8 -> alf1 : システムは\n「次へ」ボタンが押下できない

else 途中で操作をやめた場合
    co8 -> ac1 : 入力された内容までを保存する
    co8 <-- ac1

else 所蔵を選択した場合
    co8 -> ac1 : 所蔵を登録する
    co8 <-- ac1
    co8 -> wwf1 : 働き方選択画面へ移動する

end

' 9
wo1 -> wwf1 : ユーザーは働き方を選択して\n「次へ」ボタンを押下する
wwf1 -> co9 : 起動()

alt 働き方が未選択の場合
    co9 -> wwf1 : システムは\n「次へ」ボタンを押下できない

else 途中で操作をやめた場合
    co9 -> ac1 : 入力された内容までを保存する
    co9 <-- ac1

else 働き方を選択した場合
    co9 -> ac1 : 働き方を登録する
    co9 <-- ac1
    co9 -> pff1 : 都道府県選択画面へ移動する

end

' 10
wo1 -> pff1 : ユーザーは都道府県を選択し\n「保存」ボタンを押下する
pff1 -> co10 : 起動()

alt 都道府県が選択されていない場合
    co10 -> pff1 : システムは\n「次へ」ボタンを押下できない

else 途中で操作をやめた場合
    co10 -> ac1 : 入力された内容までを保存する
    co10 <-- ac1

else 都道府県を選択した場合
    co10 -> ac1 : 都道府県を登録する
    co10 <-- ac1
    co10 -> ncs1 : 通知と位置情報の設定画面に移動する

end

' 11
wo1 -> ncs1 : ユーザーは通知と位置情報の設定をし「登録」ボタンを押下する
ncs1 -> co11 : 起動()
co11 -> ac1 : 入力された情報を登録する
co11 <-- ac1
co11 -> sc1 : さがす画面に移動する

@enduml