@startuml ワーカーログイン

' 1
actor ワーカー as wo1
boundary ログイン画面 as lo1
control 表示 as co1

boundary メイン画面 as sm1
control 処理 as co2

entity ワーカーアカウント as en1

' 2
co1 -> lo1 : ログイン画面を表示する
wo1 -> lo1 : 必要情報を入力する

lo1 -> co2 : 起動:method_POST()

alt 「電話番号」が無記入の場合
    co2 -> lo1 :「電話番号が入力されていません」と\n表示する

else 「パスワード」が無記入の場合
    co2 -> lo1 :「パスワードが入力されていません」と\n表示する

else 「電話番号」「パスワード」が無記入ではない場合
    ' 分岐を書く場合は必ず「～ではない場合」を書く
    ' 参照をしたら戻り値を破線で表す
    co2 -> en1 :参照する
    en1 --> co2 
    
    alt 「電話番号」が正しくない場合
        co2 -> lo1 :「電話番号もしくはパスワードが正しくありません」と\nメッセージを表示する

    else 「パスワード」が正しくない場合
        co2 -> lo1 : 電話番号もしくはパスワードが正しくありません」と\nメッセージをを表示する

    else 「電話番号」「パスワード」が正しい場合
        co2 -> sm1 : さがす画面を表示する

    end
end    
@enduml