@startuml アカウント開設をする

' 1
actor 企業 as cp1

boundary 開設ボタン画面 as onv1
control 表示 as co1

boundary メールアドレス入力画面 as mav1
control 処理 as co2

entity メール as ml1

boundary メール送信完了画面 as msv1

' 2
co1 -> onv1 : システムは画面を表示する
cp1 -> onv1 : ユーザーは\n「無料でアカウント開設」ボタンを押下する
onv1 -> mav1 : システムは画面を表示する
cp1 -> mav1 : ユーザーは\n「求人を掲載したい（事業者の方）」ボタンを押下し、\n「上記の各事項に同意する」をチェックしてメールアドレスを入力し、\n「求人掲載用アカウント開設」ボタンを押下する

mav1 -> co2 : 起動:method_POST()


alt メールアドレスが未入力の場合
    co2 -> mav1 : システムは\n「メールアドレスを入力してください」と表示する

else メールアドレスの形式が正しくない場合
    co2 -> mav1 : システムは「メールアドレスを正しい形式で入力してください」と表示する

else 「上記の各事項に同意する」ボタンを押下せずに押下した場合
    co2 -> mav1 : システムは「アカウント開設には上記の各事項に同意が必要です。」と表示する

else すべて入力して押下した場合
    co2 -> ml1 : 送信する
    co2 <-- ml1
    co2 -> msv1 : システムは画面を表示する 

end
@enduml