@startuml 企業のアカウントを作成する

' 1
actor 企業 as cp1

boundary アカウント登録画面 as arv1 
control 表示 as co1
control 処理 as co2
boundary 事業者登録画面 as mrv1
boundary 事業者所在地登録画面 as mlv1
boundary 提出書類確認画面 as dcv1
boundary 店舗情報登録画面 as bov1
control 処理 as co3
control 処理 as co4
control 処理 as co5
control 処理 as co6

entity 企業アカウント as ac2
entity メール as ml1

boundary 登録完了画面 as rcv1
' 2
co1 -> arv1 : システムは画面を表示する:method_GET()
cp1 -> arv1 : ユーザーはアカウント情報を入力し、\n「アカウントを登録する」ボタンを押下する
arv1 -> co2 : 起動:method_POST()

alt 氏名が未入力の場合
    co2 -> arv1 : システムは\n「氏名が入力されていません」と表示する:method_GET()

else パスワードが未入力の場合
    co2 -> arv1 : システムは\n「パスワードが入力されていません」と表示する:method_GET()

else 再入力したパスワードが間違っている場合
    co2 -> arv1 : システムは\n「パスワードが間違っています」と表示する:method_GET()

else 氏名とパスワードが入力された場合
    co2 -> ac2 : 氏名とパスワードを登録する()
    co2 <-- ac2
    co2 -> mrv1 : システムは画面を表示する:method_GET()
    cp1 -> mrv1 : ユーザーは\n事業形態と業種を入力し、「次へ」ボタンを押下する
    mrv1 -> co3 : 起動:method_POST()

    alt 必須項目が未入力の場合
        co3 -> mrv1 : システムは\n「(未入力項目)が未入力です」と表示する:method_GET()

    else 必須項目が入力された場合
        co3 -> ac2 : 事業形態と業種を登録する()
        co3 <-- ac2
        co3 -> mlv1 : システムは画面を表示する:method_GET()
        cp1 -> mlv1 : 事業者情報を入力し、「登録する」ボタンを押下する
        mlv1 -> co4 : 起動:method=POST()

        alt 必須項目が未入力の場合
            co4 -> mlv1 : システムは「(未入力項目)が未入力です」と表示する:method_GET()

        else 必須項目が入力された場合
            co4 -> ac2 : 郵便番号、都道府県、市区町村名、町域・番地を登録する()
            co4 <-- ac2
            co4 -> dcv1 : システムは画面を表示する:method_GET()
            cp1 -> dcv1 : ユーザーは提出する書類を添付し、チェック項目にチェックし\n「事業者の確認のための書類を送信する」ボタンを押下する
            dcv1 -> co5 : 起動:method_POST()

            alt 個人事業主の場合
                co5 -> dcv1 : システムは選択項目に「個人番号が見えていないことを確認しました」を追加する:method_GET()

            else ファイルが提出されていない場合
                co5 -> dcv1 : システムは「ファイルが添付されていません」と表示する:method_GET()

            else 確認項目にチェックされていない場合
                co5 -> dcv1 : システムは「チェックがされていません」と表示する:method_GET()

            else ファイル提出とチェックがされている場合
                co5 -> ml1 : ファイルを送信する()
                co5 <-- ml1
                co5 -> bov1 : システムは画面を表示する:method_GET()
                cp1 -> bov1 : ユーザーは店舗情報を入力し、「店舗を登録する」を押下する
                bov1 -> co6 : 起動:method=POST()

                alt 必須項目が未入力の場合
                    co6 -> bov1 : システムは「(未入力項目)が未入力です」と表示する:method_GET()
                    
                else 「事業者の所在地を反映する」ボタンを押下した場合
                    co6 -> bov1 : システムは事業者の所在地を店舗情報に反映する:method_GET()
                
                else 必須項目が全て入力された場合
                    co6 -> ac2 : 店名、業務内容、\n郵便番号、都道府県、市区町村名、\n町域・番地を登録する()
                    co6 <-- ac2
                    co6 -> rcv1 : システムは画面を表示する:method_GET()

                end

            end

        end

    end

end
@enduml