@startuml ワーカーログイン

' 1
actor 運営 as ce1
boundary ログイン画面 as lo1
control 表示 as co1

boundary メイン画面 as sm1
control 処理 as co2

entity 運営 as en1

' 2
co1 -> lo1 : ログイン画面を表示する
ce1 -> lo1 : 必要情報を入力する

lo1 -> co2 : 起動:method_POST()
co2 -> en1 : 運営アカウントを参照する
en1 --> co2 

alt 「ID」が無記入の場合
    co2 -> lo1 :「IDが入力されていません」と\n赤文字でメッセージを表示する:method_GET()

else 「Pass」が無記入の場合
    co2 -> lo1 :「パスワードが入力されていません」と\n赤文字でメッセージを表示する:method_GET()

else 「ID」「Pass」が無記入ではない場合
    ' 分岐を書く場合は必ず「～ではない場合」を書く
    ' 参照をしたら戻り値を破線で表す
    co2 -> en1 :参照する
    en1 --> co2 
    
    alt 「ID」が正しくない場合
        co2 -> lo1 :「IDもしくはパスワードが正しくありません」と\n赤文字でメッセージを表示する:method_GET()

    else 「Pass」が正しくない場合
        co2 -> lo1 : IDもしくはパスワードが正しくありません」と\n赤文字でメッセージをを表示する:method_GET()

    else 「ID」「Pass」が正しい場合
        co2 -> sm1 : 画面を表示する:method_GET()

    end
end    
@enduml