@startuml 応募審査をする

actor    運営         as mm1
boundary 応募審査画面  as ap1
control  表示         as co1
entity   企業         as cop1

co1 -> cop1 : 企業を参照する
cop1 --> co1

alt 応募企業がない場合 
    co1 -> ap1 : システムは「応募企業はまだありません」と表示する

else 企業がある場合
    co1 -> ap1 : 応募企業一覧を表示する
    
    mm1 -> ap1 : 「絞り込み」ボタンを押下する

    ap1 -> ap1 : 絞り込み画面を表示

    mm1 -> ap1 : 絞り込みの条件を設定し「OK」ボタンを押下する

    ap1 -> co1 : 起動(POST)

    co1 -> cop1 : 企業を参照する
    cop1 --> co1

    co1 -> ap1 : 絞り込み結果の応募企業一覧を表示する

    mm1 -> ap1 : 企業の「ステータス」ボタンを押下する

    ap1 -> co1 : 起動(POST)

    co1 -> cop1 : 企業のステータスを更新する
    cop1 --> co1

    co1 -> ap1 : ステータス更新後の画面を表示する


end

@enduml