@startuml 求人の掲載をする

actor 店舗 as cp1
boundary 求人ひな型画面 as b1
control 表示 as co1
boundary 求人作成画面 as b2
control 処理 as co2
boundary 求人確認画面 as b3
control 処理 as co3

entity 求人 as en2
boundary 求人詳細画面 as b5

co1 -> en2 : 求人を参照する
co1 <-- en2 
b1   <- co1 : 画面を表示する
cp1  -> b1 : ユーザーは「このひな形を元に求人を作成」\nボタンを押下する
b1   -> b2 : 画面を表示する
cp1  -> b2 :ユーザーは必要情報を入力し\n「入力した求人内容を確認」\nボタンを押下する
b2 -> co2 : 起動:method=POST()

alt 「ひな型内容の個別設定」を押下した場合
    co2 -> b2 :個別設定画面を表示する

    alt 必須項目が未入力の場合
        b2  <- co2 :「（未入力項目）が未入力です」\nと画面に表示する

    else すべて入力された場合
        b2 -> b3 : 画面を表示する:method_GET()

        alt 求人内容を変更する場合
            b3 -> b2 : 求人作成画面を表示する

        else 求人内容の変更がない場合    
            cp1 -> b3 : ユーザーは「休業手当に関する事項を確認しました」\nにチェックし、「求人公開」ボタンを押下する
            b3 -> co3 : 起動:method_POST()

            alt チェックが押下されていない場合
                co3 -> b3 : 「チェック項目にチェックされていません」\nと表示する

            else チェックが押下された場合
                co3 -> en2 : 求人登録()
                en2 --> co3
                co3 -> b5 : 画面を表示:method_GET()
            end
        end
    end
end


@enduml