@startuml 求人のひな形を作成する

actor 店舗 as cp1
boundary ひな形一覧画面 as b1
control 表示 as co1
boundary 新規作成画面 as b2
control 処理 as co2
boundary かんたん自動入力画面 as b3
control 処理 as co3

entity 求人のひな形 as en1
boundary ひな型作成完了画面 as b4

b1 <- co1 : 画面を表示する
cp1 -> b1 :ユーザーは「＋求人のひな形を新規作成」\nを押下する
b1 -> b2 : 画面を表示する:method_GET()

alt 「かんたん自動入力」ボタンを押下した場合
    b2 -> b3 : かんたん自動入力画面\nを表示:method_GET()
    cp1 -> b3 : ユーザーは業種と職種を選択する
    b3 -> co3 : 起動:method_POST()

    alt 業種または職種が未選択の場合
        co3 -> b3 : システムは\n「業種または職種を選択してください」と表示する

    else 選択して「求人のひな形の作成を完了」ボタンを押下した場合
        co3 -> en1 : 求人のひな形を作成する
        co3 <-- en1
        co3 -> b4 : システムは画面を表示する

    end

else 手動で入力した場合
    cp1 -> b2 : ユーザーは必要情報を入力し、\n「求人のひな形を作成を完了」ボタンを押下する
    b2 -> co2 : 起動:method_POST()

    alt 未入力項目がある場合
    co2 -> b2 : 「（未入力項目）が未入力です」\nと画面に表示する



    else 項目をすべて入力して「求人のひな形の作成を完了」ボタンを押下した場合
        co2 -> en1 : 求人のひな形を作成
        co2 <-- en1
        co2 -> b4 : システムは画面を表示する

    end
end


@enduml