@startuml ワーカーを評価する

actor 店舗 as cp1
boundary レビュー必要求人一覧画面 as b1
control 表示 as co1
boundary レビュー入力画面 as b2
control 処理 as co2 
boundary まとめてレビューを入力画面 as b3
control 処理 as co3
entity 店舗からの評価 as en1
boundary 完了画面 as b4

b1 <- co1 : 画面を表示する:method_GET()
cp1 -> b1 : ユーザーはワーカーの\n「レビュー」ボタンを表示する
b1 -> b2 :画面を表示する:method_GET()

alt 1人ずつ評価する場合
    cp1 -> b2 : ユーザーは必要情報を入力し、\n「レビューを送信する」ボタンを押下する
    b2 -> co2 : 起動:method_POST()
    
    alt 評価項目が未入力の場合
        co2 -> b2 : 「(未入力項目)の評価項目が未入力です」\nと表示する

    else 評価がすべて入力した場合
        co2 -> en1 : レビューを送信する
        co2 <-- en1
        co2 -> b4 : システムは画面を表示する
    
    end

else 「まとめてレビューを入力」を押下した場合
    b2 -> b3 : 画面を表示する:method_GET()
    cp1 -> b3 : ユーザーはレビューを入力し、\n「まとめて入力」ボタンを押下する
    b3 -> co3 : 起動:method_POST()

    alt 評価項目が未入力の場合
            b3 <- co3 :「(未入力項目)の評価項目が未入力です」\nと画面に表示する

    else 評価を全て入力した場合
            co3 -> en1 : レビューを送信する()
            co3 <-- en1

            co3 -> b4 : システムは画面を表示する
    end
end

@enduml