@startuml マッチングしたワーカーの確認をする

actor 店舗 as cp1

boundary 求人詳細画面 as b1
control 表示 as co1
boundary ワーカー一覧画面 as b2
boundary ワーカー詳細画面 as b3
boundary キャンセル画面 as b4
boundary キャンセル最終確認画面 as b5
control 処理 as co2
control 処理 as co3
control 処理 as co4

entity ワーカー as wo1
entity 求人 as jb1
boundary 完了画面 as b6

co1 -> jb1 : 求人の詳細を参照する
co1 <-- jb1
co1 -> b1 : 画面を表示する
cp1 -> b1 : ユーザーは「ワーカーの確認」ボタンを押下する
b1 -> co2 : 起動:method=POST()

alt マッチングしたワーカーがいない場合
    co2 -> b2 : システムは\n「マッチングしたワーカーがいません」と表示する

else マッチングしたワーカーがいる場合
    co2 -> wo1 : ワーカーの情報を参照する
    co2 <-- wo1
    co2 -> b2 : システムは画面を表示する

        cp1 -> b2 : ユーザーは「氏名」を押下する
        b2 -> co3 : 起動:method=POST()
        co3 -> wo1 : ワーカーの詳細を参照する
        co3 <-- wo1
        co3 -> b3 : システムは\n画面を表示する:method=GET()

end
@enduml