@startuml マッチングしたワーカーの確認をする

actor 店舗 as cp1
boundary 求人一覧画面 as b1
control 表示 as co1
boundary 求人タイトル画面 as b2
boundary 求人詳細画面 as b3
control 処理 as co2
boundary ワーカー一覧画面 as b4
control 処理 as co3
boundary ワーカー詳細画面 as b5
control 処理 as co4
boundary キャンセル画面 as b6

entity ワーカー as wo1
entity 求人 as jb1

co1 -> jb1 : 求人を参照する()
co1 <-- jb1
b1 <- co1 : システムは画面を表示する()

alt カレンダーから確認する場合
    cp1 -> b1 : ユーザーは表示したい日付を押下する
    b1 -> b2 : システムは画面を表示する:method_GET()
    cp1 -> b2 : ユーザーは確認したい「求人の詳細」ボタンを押下する
    b2 -> co2 : 起動:method_POST()
    
    alt 削除済み求人の場合
        co2 -> b3 : システムは\n「この求人は削除されています」と表示する
    
    else 詳細がある場合
        co2 -> jb1 : 求人の詳細を参照する
        co2 <-- jb1
        co2 -> b3 : システムは求人の詳細を表示する
        cp1 -> b3 : ユーザーは\n「ワーカーを確認」ボタンを押下する
        b3 -> co3 : 起動:method_POST()

        alt マッチングワーカーがいない場合
            co3 -> b4 : システムは\n「ワーカーがいません」と表示する

        else マッチングワーカーがいる場合
            co3 -> wo1 : ワーカーを参照する()
            co3 <-- wo1
            co3 -> b4 : システムは画面を表示する
            cp1 -> b4 : ユーザーは確認したいワーカーの詳細を押下する
            b4 -> co4 : 起動:method_POST()
            co4 -> wo1 : ワーカーの詳細を参照する
            co4 <-- wo1
            co4 -> b5 : システムは画面を表示する
        
        end

    end

else リストから確認する場合
    cp1 -> b1 : ユーザーはリストを押下する
    b1 -> b1 : システムは求人をリスト表示にする
    cp1 -> b1 : ユーザーは確認したい「求人の詳細」ボタンを押下する
    b1 -> co2 : 起動:method_POST()

    alt 削除済み求人の場合
        co2 -> b3 : システムは\n「この求人は削除されています」と表示する
    
    else 詳細がある場合
        co2 -> jb1 : 求人の詳細を参照する
        co2 <-- jb1
        co2 -> b3 : システムは画面を表示する:method_GET()
        cp1 -> b3 : ユーザーは\n「ワーカーを確認」ボタンを押下する
        b3 -> co3 : 起動:method_POST()

        alt マッチングワーカーがいない場合
            co3 -> b4 : システムは\n「ワーカーがいません」と表示する

        else マッチングワーカーがいる場合
            co3 -> wo1 : ワーカーを参照する()
            co3 <-- wo1
            co3 -> b4 : システムは画面を表示する:method_GET()
            cp1 -> b4 : ユーザーは確認したいワーカーの詳細を押下する
            b4 -> co4 : 起動:method_POST()
            co4 -> wo1 : ワーカーの詳細を参照する
            co4 <-- wo1
            co4 -> b5 : システムは画面を表示する:method_GET()
        
        end

    end

end

alt マッチングをキャンセルする場合
    cp1 -> b4 : キャンセルしたいワーカーから\n「キャンセル」ボタンを押下する
    b4 -> b6 : システムは画面を表示する:method

else 複数人のマッチングをキャンセルする場合

end

    
@enduml