@startuml 修正依頼の確認、承認をする

actor 店舗 as cp1
boundary 修正依頼ホーム画面 as b1
control 表示 as co1
boundary 修正依頼確認画面 as b2
control 処理 as co2
boundary 承認画面 as b3
control 処理 as co3
boundary 拒否画面 as b4
control 処理 as co4

entity 修正依頼 as cr1
entity ワーカー as wo1
entity 求人 as jb1
boundary 完了画面 as b5

co1 -> cr1 : 修正依頼を参照する()
co1 <-- cr1
co1 -> b1 : 画面を表示する

alt 修正依頼がない場合
    co1 -> b1 : システムは\n「修正依頼はありません」と\n表示する:method=GET()

else 修正依頼がある場合
    co1 -> wo1 : ワーカーを参照する()
    co1 <-- wo1
    co1 -> jb1 : 求人を参照する()
    co1 <-- jb1
    co1 -> b1 : システムは\n修正依頼のある求人とワーカー名を表示する:method=GET()

    cp1 -> b1 : ユーザーは「ワーカー」ボタンを押下する
    b1 -> b2 : 画面を表示する:method=GET()
    cp1 -> b2 : ユーザーは「承認」または「拒否」ボタンを押下する

    alt 拒否ボタンを押下した場合
        b2 -> b4 : 画面を表示する:method=GET()
        cp1 -> b4 : ユーザーは拒否の理由を記入し\n「拒否する」ボタンを押下する
        b4 -> co4 : 起動:method=POST()

        alt メッセージが入力されていない場合
            co4 -> b4 : システムは\n「メッセージが入力されていません」と表示する:method=GET()
        
        else メッセージが入力された場合
            co4 -> cr1 : 修正依頼を拒否()
            co4 <-- cr1
            co4 -> wo1 : ワーカーに修正依頼の拒否を送信()
            co4 <-- wo1
            co4 -> b5 : システムは画面を表示する:method=GET()

        end

    else 承認ボタンを押下した場合
        b2 -> b3 : 画面を表示する:method=GET()
        cp1 -> b3 : ユーザーは\nチェックボックスにチェックし「承認する」ボタンを押下する
        b3 -> co3 : 起動:method=POST()

        alt チェックボックスにチェックしてない場合
            co3 -> b3 : システムは「チェック項目にチェックされていません」と表示する:method=GET()

        else チェック項目にチェックされた場合
            co3 -> cr1 : 修正依頼を承認()
            co3 <-- cr1
            co3 -> wo1 : ワーカーに修正依頼の承認を送信()
            co3 <-- wo1
            co3 -> b5 : システムは画面を表示する:method=GET()

        end

    end


end


@enduml