@startuml 店舗の情報を設定する

actor 店舗 as cp1
boundary ホーム画面 as b1
control 表示 as co1
boundary 店舗情報画面 as b2
control 処理 as co2
boundary 変更画面 as b3
control 処理 as co3

entity 店舗 as en1
boundary 完了画面 as b4

co1 -> b1 : 画面を表示する:
cp1 -> b1 :「店舗情報」ボタンを押下する
b1 -> co2 : 起動する:method=POST()
co2 -> en1 :参照する()
co2 <-- en1
co2 -> b2 :画面を表示する:method=GET()
cp1 -> b2 :「変更」ボタンを押下する
b2 -> b3 :画面を表示する:method=GET()
cp1 -> b3 :変更内容を入力し、「保存」ボタンを押下する
b3 -> co3 : 起動:method=POST()

alt 電話番号が未入力の場合
b3 <- co3 :システムは\n「電話番号が未入力です」と\n画面に表示する:method=GET()

else 問題がない場合
co3 -> en1 : 電話番号を変更する()
co3 <-- en1
co3 -> b4 : 画面を表示する:method=GET()

end

@enduml