@startuml QRコードを印刷する

actor 店舗 as cp1
boundary 管理画面 as b1
control 表示 as co1
control 処理 as co2
boundary QRコード画面 as b2
control 処理 as co3

entity 店舗 as b1
boundary QRコード印刷完了画面 as b3

b1   <- co1
cp1  -> b1 :サイドメニューの\n「チェックイン/アウト管理」を押下
b1   -> co2 :起動する:method=POST()
co2  -> en1 :参照する()
co2 <-- en1
b2  <- co2 :QRコードを表示する()
cp1 -> b2 :「QRコードを印刷する」ボタンを押下
b2 -> co3 :印刷処理()
co3 -> b3 :画面を表示する

@enduml