@startuml 今後の予定を閲覧する
' 1
actor ワーカー as wo1
boundary はたらく画面 as wk1
control 表示 as co1

entity 今後の予定 as sh1

' 2
co1 -> sh1 : 今後の予定を参照する()
co1 <-- sh1
co1 -> wk1 :システムは画面を表示する

alt 応募済みの仕事がない場合
    co1 -> wk1 : システムは「今後の予定がありません」\n「次のお仕事を探してみましょう」と\n「仕事を探す」ボタンを表示する:method_GET()


end

@enduml