@startuml 過去の業務と報酬を閲覧する
' 1
actor ワーカー as wo1
boundary はたらく画面 as wk1
control 表示 as co1
boundary これまでの仕事画面 as ks1
boundary 求人詳細画面 as jd1

entity これまでの仕事 as aj1
' 2
co1 -> wk1 : 表示する
wo1 -> wk1 :  ユーザーは「これまでの仕事」ボタンを押下する
alt これまでの仕事がない場合
wk1 -> ks1 : システムは「これまでの仕事はありません」と表示する
else 仕事がある場合
wk1 -> ks1 : 表示する
wo1 -> ks1 : ユーザーは過去の業務を選択する
ks1 -> jd1 : 表示する
end

@enduml