@startuml SQ_ログアウト

' モノ
actor 店舗 as sh1
boundary "メイン画面" as menu
control "表示" as co1
boundary "ログイン画面" as log

' 流れ
co1 -> menu : メインメニュー画面を表示する
ce1 -> menu : ログアウトボタンを押下する
menu -> log : ログイン画面を表示する

@enduml