@startuml ウォレット残高を引き出す

' 1
actor ワーカー as wo1

boundary マイページ画面 as bo1
control 表示 as co1
boundary 報酬管理 as bo2
boundary 報酬申請 as bo3 
boundary 報酬確認 as bo4
boundary 報酬確定 as bo5
boundary 入出金履歴 as bo6
boundary 振込先口座登録 as bo7
boundary 振込先口座編集 as bo8

control 処理 as co2
control 処理 as co3
control 処理 as co4
control 処理 as co5

entity ワーカー as en1
entity 銀行口座 as en2
entity 企業 as en3


co1 -> bo1 : 画面を表示する
wo1 -> bo1 :「引き出す」ボタンを押下する
bo1 -> co2 : 起動:method=POST()
co2 -> en1 : ワーカーを参照()
en1 --> co2
co2 -> en2 : 残高を参照する()
co2 <-- en2
co2 -> bo2 : 画面を表示する:method_GET()

alt ユーザーが「入出金履歴」を押下した場合
  wo1 -> bo2 :「入出金履歴」ボタンを押下する
  bo2 -> co2 : 起動:method=POST()

  alt 入出金履歴がない場合
    co5 -> bo6 : 「履歴がありません」と表示する:method_GET()
  
  else 入出金履歴がある場合
    co5 -> en1 : 入出金履歴を参照する()
    co5 <-- en1
    co5 -> bo6 : 画面を表示する:method_GET()

  end

  else 振込先口座を登録を押下した場合
    wo1 -> bo2 : 「振込先口座を登録」を押下する
    bo2 -> co2 : 起動:method=POST()
    co2 -> en1 : ワーカーを参照()
    en1 --> co2
    co2 -> bo7 : 画面を表示:method_GET()

  else 振込先口座を編集を押下した場合
    wo1 -> bo2 : 「振込先口座を編集」を押下する
    bo2 -> co2 : 起動:method=POST()
    co2 -> en1 : ワーカーを参照()
    en1 --> co2
    co2 -> bo8 : 画面を表示:method_GET()



else  「振り込み申請」ボタンを押下した場合
  wo1 -> bo2 :「振り込み申請」ボタンを押下する
  bo2 -> co3 : 起動:method=POST()
  co3 -> en2 : 振込先口座を参照する()
  co3 <-- en2
  co3 -> bo3
  wo1 -> bo3 : 「申請」ボタンを押下する
  bo3 -> bo4 : 画面を表示する:method=GET()
  wo1 -> bo4 : 「OK」ボタンを押下する
  bo4 -> co5 : 起動:method_POST()
  co5 -> en3 : 企業に申請する()
  co5 <-- en3
  co5 -> bo5 : 画面を表示する:method_GET()

end

@enduml