@startuml あなたの実績を閲覧する

actor ワーカー as wo1

boundary マイページ画面 as bo1
control 表示 as co1
boundary 実績画面 as bo2

control 処理 as co2

entity 実績 as en1

co1 -> bo1:画面を表示する()
wo1 -> bo1:「あなたの実績」ボタンを押下する
bo1 -> co2:起動:method=POST()

alt 働いたことがない場合
    co2 -> bo2:システムは\n「獲得したEXPはありません」と表示する

else 働いたことがある場合
    co2 -> en1:実績を参照()
    en1 --> co2
    co2 -> bo2:画面を表示する:method_GET()

end

@enduml