@startuml バッチ一覧を閲覧する

actor ワーカー as wo1

boundary マイページ画面 as bo1
control 表示 as co1
boundary バッチ一覧画面 as bo2
boundary バッチ詳細画面 as bo3

control 処理 as co2
control 処理 as co3

entity バッチ as en1
entity 求人 as en2 

co1 -> bo1:画面を表示する()
wo1 -> bo1:ユーザーは\n「バッチ一覧」ボタンを押下する
bo1 -> co2:起動:method=POST()
co2 -> en1:バッチを参照する()
en1 --> co2

co2 -> bo2:ユーザーは画面を表示する()

wo1 -> bo2:「バッチ詳細」ボタンを押下する
bo2 -> co3:起動():method=POST()

@enduml