@startuml バッチ一覧を閲覧する

actor ワーカー as wo1

boundary マイページ画面 as bo1
boundary バッチ一覧画面 as bo2
boundary バッチ詳細画面 as bo3

control 表示 as co1
control 処理 as co2

entity ワーカーアカウント as en1

co1 -> bo1:表示()
wo1 -> bo1:「バッチ一覧」ボタンを押下する
bo1 -> co2:起動()
co2 -> en1:参照()
en1 --> co2

co2 -> bo2:表示()

wo1 -> bo2:「バッチ詳細」ボタンを押下する
bo2 -> co2:起動()

alt バッチを獲得していない場合
    co2 -> bo3:「「バッジを獲得できる可能性がある仕事」を表示する

else
    co2 -> bo3:表示()
    
end

@enduml