@startuml お問い合わせをする

actor ワーカー as wo1

boundary マイページ画面 as bo1
control 表示 as co1
boundary 問い合わせ説明画面 as bo2
boundary お問い合わせ画面 as bo3

control 処理 as co2

entity 運営 as en1

co1 -> bo1:画面を表示する()
wo1 -> bo1:ユーザーは\n「お問い合わせ」ボタンを押下する
bo1 -> bo2:画面を表示する:method=GET()
wo1 -> bo2:ユーザーは\n「お問い合わせフォーム」ボタンを入力する
bo2 -> bo3:画面を表示する:method=GET()

wo1 -> bo3:ユーザーは\nメールアドレスとワーカーか事業者か\nと問い合わせ内容を入力し、\n「送信」ボタンを押下する
bo3 -> co2:起動:method=POST()
alt 未入力箇所がある場合
    co2 -> bo3:システムは\n「(未入力部分)が入力されていませんと」表示する

else 全て入力されている場合
    co2 -> en1:運営に送信する()
    co2 <-- en1
    co2 -> bo1:画面を表示する:method=GET()

end

@enduml