@startuml お問い合わせをする

actor ワーカー as wo1

boundary マイページ画面 as bo1
control 表示 as co1
boundary 問い合わせ説明画面 as bo2
boundary お問い合わせ画面 as bo3

control 処理 as co2

entity 運営 as en1

co1 -> bo1:画面を表示する
wo1 -> bo1:「お問い合わせ」ボタンを押下する
bo1 -> bo2:画面を表示する:method=GET()
wo1 -> bo2:「お問い合わせフォーム」ボタンを押下する
bo2 -> bo3:画面を表示する:method=GET()

wo1 -> bo3:問い合わせ内容を入力し、「送信」ボタンを押下する
bo3 -> co2:起動:method=POST()

co2 -> en1:問い合わせ内容を送信する()
co2 <-- en1
co2 -> bo3:「送信が完了しました」と\n表示する:method=GET()

@enduml