@startuml 退会手続きをする

actor ワーカー as wo1

boundary マイページ画面 as bo1
control 表示 as co1
boundary 退会理由選択画面 as bo2
boundary 退会理由アンケート画面 as bo3
boundary 退会理由アンケート画面 as bo4
boundary 退会確認画面 as bo5
boundary アカウント作成画面 as bo6

control 処理 as co2
control 削除 as co3

entity ワーカー as en1
entity 求人 as en3


co1 -> bo1:画面を表示する
wo1 -> bo1:「退会手続き」ボタンを押下する
bo1 -> bo2:画面を表示する:method=GET()

alt 「ご希望のエリアが対応外だった」ボタンを押下した場合
    wo1 -> bo2:「ご希望のエリアが対応外だった」ボタンを押下する
    bo2 -> bo3:画面を表示する:method=GET()

else 「その他の理由で退会を希望する場合」ボタンを押下した場合
    wo1 -> bo2:「その他の理由で退会を希望する場合」ボタンを押下する
    bo2 -> bo3:画面を表示する:method=GET()

end

wo1 -> bo2:「次へ」ボタンを押下する
bo2 -> bo5:画面を表示する:method=GET()
wo1 -> bo5:「退会する」ボタンを押下する
bo5 -> co2:起動:method=GET()





alt ウォレットに引き出し可能額がある場合
    co2 -> en1:ウォレット残高を参照する()
    co2 <-- en1
    co2 -> bo5:「ウォレットに引き出し可能な額があるため退会できません」と表示する:method=GET()

else 確定済みの募集がある場合
    co2 -> en3:求人を参照する()
    co2 <-- en3
    co2 -> bo5:「確定済みの募集があるため退会できません」と表示する:method=GET()

else 退会可能な場合
    co2 -> en1:ワーカーを参照する()
    en1 --> co2
    co3 -> en1:ワーカーを削除する()
    co3 <-- en1
    co3 -> bo6:画面を表示する:method=GET()

end

@enduml