@startuml ミュートしている店舗の設定をする

actor ワーカー as wo1

boundary マイページ画面 as bo1
control 表示 as co1
boundary ミュート企業一覧画面 as bo2

control 処理 as co2

entity ミュートしている店舗 as en1

co1 -> bo1:画面を表示する
wo1 -> bo1:「ミュートにしている店舗」ボタンを押下する
bo1 -> co2:起動:method=POST()

alt ミュートにしている店舗がない場合
    co2 -> bo2:「ミュートにしている店舗はありません」と表示する:method=GET()

else ミュートにしている店舗がある場合
    co2 -> en1:ミュートしている店舗を参照する()
    en1 -> co2
    co2 -> bo2:画面を表示する:method=GET()

end

@enduml