@startuml 退会手続きをする

actor ワーカー as wo1

boundary マイページ画面 as bo1
boundary 退会理由選択画面 as bo2
boundary 退会理由アンケート画面 as bo3
boundary 退会理由アンケート画面 as bo4
boundary 退会確認画面 as bo5
boundary アカウント作成画面 as bo6

control 表示 as co1
control 処理 as co2
control 削除 as co3

entity ワーカーアカウント as en1

co1 -> bo1:表示()
wo1 -> bo1:「退会手続き」ボタンを押下する
bo1 -> bo2:表示()

alt 「ご希望のエリアが対応外だった」ボタンを押下した場合
    wo1 -> bo2:「ご希望のエリアが対応外だった」ボタンを押下する
    bo2 -> bo3:表示()

else 「その他の理由で退会を希望する場合」ボタンを押下した場合
    wo1 -> bo2:「その他の理由で退会を希望する場合」ボタンを押下する
    bo2 -> bo3:表示()

end

wo1 -> bo2:「次へ」ボタンを押下する
bo2 -> bo5:表示()
wo1 -> bo5:「退会する」ボタンを押下する
bo5 -> co2:起動()
co2 -> en1:参照()
en1 --> co2

alt ペナルティポイントが2以上の場合
    co2 -> bo5:「ペナルティポイントが２ポイント以上のため退会できません」と表示する

else 申し込みが制限されている場合  
    co2 -> bo5:「申し込み制限中のため退会できません」と表示する

else ウォレットに引き出し可能額がある場合
    co2 -> bo5:「ウォレットに引き出し可能な額があるため退会できません」と表示する

else 確定済みの募集がある場合
    co2 -> bo5:「確定済みの募集があるため退会できません」と表示する

else 退会可能な場合
    co2 -> co3:起動()
    co3 -> en1:削除()
    co3 -> bo6:表示()

end

@enduml