@startuml AccountSettings

actor ユーザー as a1
boundary アカウント設定画面 as b1
' 最初の画面を表示する為のビューを用意
control 表示ビュー as c1
' 処理が必要な場合のビューを追加
control 処理ビュー as c2
boundary 電話番号確認画面 as b2
boundary 登録済み番号入力画面 as b3
' 代替フロー用の処理を行う為のビューを追加
control 処理ビュー as c3
boundary 新しい電話番号の登録画面 as b4
' 代替フロー用の処理を行う為のビューを追加
control 処理ビュー as c4
boundary 認証コード入力画面 as b5
control 処理ビュー as c5
'データ
entity ユーザー情報 as e1
entity 認証コード発行履歴 as e2

' プロフィール編集画面
boundary プロフィール編集画面 as b6

' その他のプロフィール画面
boundary その他のプロフィール画面 as b7
boundary 所属選択画面 as b8

' 緊急連絡先画面
boundary 緊急連絡先画面 as b9

' 働き方設定画面
boundary 働き方設定画面 as b10 

c1 -> b1: 画面を表示()
a1 -> b1: 「アカウント設定」ボタンを押下
b1 -> b1: 画面を表示:method()=GET

a1 -> b1: ボタンを押下

alt 「電話番号」ボタンを押下した場合
    b1 -> c2: 起動():method()=GET
    c2 -> e1: 電話番号確認要求()
    e1 --> c2: 
    c2 -> b1: 画面を表示()
    a1 -> b2: 「変更」ボタンを押下
    b2 -> b3: 画面を表示:method()=GET

    a1 -> b3: 登録済み番号を入力し「次へ」ボタンを押下
    b3 -> c3: 起動():method()=POST
    alt 電話番号が違う場合
        c3 -> b3: 「入力した電話番号が登録時と違います」\nと表示する()

    else 電話番号を3回間違えた場合
        c3 -> b3: 「電話番号の確認に失敗しました。\n時間をおいて再度お試しください」と表示する()

    else 登録済みの電話番号の入力で一定時間操作されなかった場合
        c3 -> b3: 「変更操作の有効期限切れです」と表示する()

    else 番号が正しい場合
        c3 -> b4: 画面を表示()

        a1 -> b4: 新しい電話番号を入力し「次へ」ボタンを押下
        b4 -> c4: 起動():method()=POST
        c4 -> e1: 電話番号の使用可否確認要求()
        e1 --> c4:
        alt 電話番号が使えない場合
            c4 -> b4: 「「この電話番号は使用できません」\nと表示する()

        else 登録済みの電話番号を入力した場合
            c4 -> b4: 「同じ電話番号です」と表示する()

        else すでに同じ電話番号で登録されている場合
            c4 -> b4: 「この電話番号は登録できません」\nと表示する()

        else 電話番号が正しい場合
            b4 -> b5: 画面を表示:method()=GET

            a1 -> b5: 認証コードを入力し「OK」ボタンを押下（画面内ポップで処理完了）
            b5 -> c5: 起動():method()=POST
            c5 -> e2: 認証コード確認要求()
            e2 --> c5:
            alt 認証コードが違う場合
                c5 -> b5: 「認証コードが違います」と表示する()

            else 認証コードの入力回数が上限に達した場合
                c5 -> b5: 「もう一度発行が必要です」と表示する()

            else 認証コードが正しい場合
                c5 -> b5: 画面を表示する()（画面内ポップを表示）
                a1 -> b5: 「OK」ボタンを押下
                b5 -> b1:  画面を表示:method()=GET
            end
        end
    end

else 「プロフィール編集」ボタンを押下した場合
    b1 -> c1: 起動():method()=GET
    c1 -> e1: 参照()
    e1 --> c1:
    c1 -> b6: 画面を表示()

    a1 -> b6: 必要情報を入力し「変更を保存」ボタンを押下する
    b6 -> c1: 起動():method()=POST
    c1 -> e1: 更新()
    e1 --> c1:
    c1 -> b6: 画面を表示()

else 「その他のプロフィール」ボタンを押下した場合
    b1 -> c1: 起動():method()=GET
    c1 -> e1: 参照()
    e1 --> c1:
    c1 -> b7: 画面を表示()

    a1 -> b7: 「所属」ボタンを押下する
    b7 -> b8: 画面を表示:method()=GET

    a1 -> b8: 所属を選択し「OK」ボタンを押下する
    b8 -> c1: 起動():method()=POST
    c1 -> e1: 更新()
    e1 --> c1:
    c1 -> b7: 画面を表示()

else 「緊急連絡先」ボタンを押下した場合
    b1 -> c1: 起動():method()=GET
    c1 -> e1: 参照()
    e1 --> c1:
    c1 -> b9: 画面を表示()

    a1 -> b9: 必要情報を入力し「OK」ボタンを押下する
    b9 -> c1: 起動():method()=POST
    c1 -> e1: 更新()
    e1 --> c1:
    c1 -> b9: 画面を表示()

else 「働き方」ボタンを押下した場合
    b1 -> c1: 起動():method()=GET
    c1 -> e1: 参照()
    e1 --> c1:
    c1 -> b10: 画面を表示()

    a1 -> b10: 必要情報を入力し「保存」ボタンを押下する
    b10 -> c1: 起動():method()=POST
    c1 -> e1: 更新()
    e1 --> c1:
    c1 -> b10: 画面を表示()

end


@enduml

