@startuml メッセージでやり取りする
' 1
actor ワーカー as wo1
boundary メッセージ画面 as me1
control 表示 as co1
boundary チャット画面 as ch1

' 2
alt メッセージを送る相手がいない場合
co1 -> me1 : システムは「メッセージがありません」と表示する
else メッセージをする相手がいる場合
co1 -> me1 : 表示する
wo1 -> me1 : ユーザーはメッセージを送る店舗を選択する
me1 -> ch1 : 表示する
wo1 -> ch1 : ユーザーはメッセージを入力し、「送信」ボタンを押下する
alt テキストボックスに何も入力されていない場合
ch1 -> ch1 : ユーザーは「送信」ボタンを押下できない
else テキストボックスに入力がされている場合
ch1 -> ch1 : メッセージを送る

end
end

@enduml