@startuml メッセージでやり取りする
' 1
actor ワーカー as wo1
boundary メッセージ画面 as me1
control 表示 as co1
boundary チャット画面 as ch1
control 処理 as co2

entity メッセージ as ml1
entity 店舗 as ac2

' 2
co1 -> ac2 : 店舗を参照する()
co1 <-- ac2

alt マッチングしてない場合
    co1 -> me1 : システムは「メッセージはありません」と表示する
else マッチングしている場合
    co1 -> me1 : システムは画面を表示する()
    wo1 -> me1 : ユーザーはマッチング店舗を選択する
    me1 -> ch1 : システムは画面を表示する()
    wo1 -> ch1 : ユーザーはメッセージを入力し「送信」ボタンを押下する
    ch1 -> co2 : 起動:method=POST()

    alt テキストボックスに何も入力されていない場合
        co2 -> ch1 : システムは「メッセージを入力してください」と表示する
    else テキストボックスに入力がされている場合
        co2 -> ml1 : メールを送信()
        co2 <-- ml1
        co2 -> ch1 : システムは「メッセージを送信しました」と表示する
    end
end

@enduml