@startuml メッセージでやり取りする
' 1
actor ワーカー as wo1
boundary メッセージ画面 as me1
control 表示 as co1
boundary チャット画面 as ch1
control 処理 as co2

entity メール as ml1

' 2
co1 -> me1 : システムは画面を表示する

alt メッセージを送る相手がいない場合
co1 -> me1 : システムは「メッセージがありません」と表示する
else メッセージをする相手がいる場合
co1 -> me1 : 表示する
wo1 -> me1 : ユーザーはメッセージを送る店舗を選択する
me1 -> ch1 : 画面を表示する:method_GET()
wo1 -> ch1 : ユーザーはメッセージを入力し、「送信」ボタンを押下する
ch1 -> co2 : 起動:method_POST()
alt テキストボックスに何も入力されていない場合
co2 -> ch1 : ユーザーは「送信」ボタンを押下できない
else テキストボックスに入力がされている場合
co2 -> ml1 : メールを送信()
co2 <-- ml1
co2 -> ch1 : 「メッセージを送信しました」と表示する

end
end

@enduml