# Generated by Django 5.2.10 on 2026-01-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
