# Generated by Django 5.2.10 on 2026-01-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_workerprofile_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workerprofile',
            old_name='affiliation',
            new_name='real_name',
        ),
        migrations.RemoveField(
            model_name='workerprofile',
            name='working_style',
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='is_identity_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='location_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='notifications_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
