# Generated by Django 5.2.10 on 2026-01-16 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_affiliation_workerprofile_real_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='emergency_relation',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
