# Generated by Django 5.2.10 on 2026-01-20 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_workerprofile_emergency_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='workerprofile',
            name='emergency_phone',
        ),
        migrations.RemoveField(
            model_name='workerprofile',
            name='emergency_relation',
        ),
        migrations.RemoveField(
            model_name='workerprofile',
            name='furigana',
        ),
        migrations.RemoveField(
            model_name='workerprofile',
            name='location_enabled',
        ),
        migrations.RemoveField(
            model_name='workerprofile',
            name='notifications_enabled',
        ),
        migrations.RemoveField(
            model_name='workerprofile',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='workerprofile',
            name='real_name',
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='address_line',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='番地'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='building',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='建物名・部屋番号'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='career_interest',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='正社員への興味'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='市区町村'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='face_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/faces/', verbose_name='顔写真'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='first_name_kana',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='メイ(カナ)'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='first_name_kanji',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='名(漢字)'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='is_setup_completed',
            field=models.BooleanField(default=False, verbose_name='セットアップ完了'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='last_name_kana',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='セイ(カナ)'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='last_name_kanji',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='姓(漢字)'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='郵便番号'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='target_prefectures',
            field=models.TextField(blank=True, null=True, verbose_name='希望都道府県'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='work_style',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='アルバイトの働き方'),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='生年月日'),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='is_identity_verified',
            field=models.BooleanField(default=False, verbose_name='本人確認済み'),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='prefecture',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='都道府県'),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workerprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
