# Generated by Django 5.2.10 on 2026-01-23 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_workerprofile_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='バッジ名')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='badges/', verbose_name='アイコン画像')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certified_count', models.IntegerField(default=0, verbose_name='認定回数')),
                ('certified_store_count', models.IntegerField(default=0, verbose_name='認定店舗数')),
                ('is_obtained', models.BooleanField(default=False, verbose_name='獲得済み')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.badge')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='accounts.workerprofile')),
            ],
            options={
                'unique_together': {('worker', 'badge')},
            },
        ),
    ]
