# Generated by Django 5.2.10 on 2026-01-26 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_badge_workerbadge'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='金額')),
                ('transaction_type', models.CharField(choices=[('reward', '報酬'), ('withdrawal', '出金'), ('bonus', 'ボーナス')], max_length=20, verbose_name='取引種別')),
                ('description', models.CharField(max_length=200, verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='日時')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to='accounts.workerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='銀行名')),
                ('account_type', models.CharField(default='普通', max_length=20, verbose_name='口座種別')),
                ('branch_name', models.CharField(max_length=100, verbose_name='支店名')),
                ('account_number', models.CharField(max_length=20, verbose_name='口座番号')),
                ('account_holder_name', models.CharField(max_length=100, verbose_name='口座名義')),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='accounts.workerprofile')),
            ],
        ),
    ]
