# Generated by Django 5.2.10 on 2026-01-26 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_wallettransaction_workerbankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='cancellations',
            field=models.IntegerField(default=0, verbose_name='キャンセル数'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='lastminute_cancel',
            field=models.IntegerField(default=0, verbose_name='直前キャンセル数'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='penalty',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ペナルティ'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='penalty_points',
            field=models.IntegerField(default=0, verbose_name='ペナルティポイント'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100, verbose_name='店舗名')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.workerprofile')),
            ],
        ),
    ]
