# Generated by Django 5.2.10 on 2026-01-26 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_workerprofile_cancellations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualificationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分野名')),
                ('display_order', models.IntegerField(default=0, verbose_name='表示順')),
            ],
        ),
        migrations.CreateModel(
            name='QualificationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='資格名')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.qualificationcategory')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_image', models.ImageField(upload_to='qualifications/', verbose_name='資格証明書')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.qualificationitem')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='accounts.workerprofile')),
            ],
        ),
    ]
