# Generated by Django 5.2.10 on 2026-01-27 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_qualificationcategory_qualificationitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_good',
            field=models.BooleanField(default=True, verbose_name='Good評価'),
        ),
        migrations.CreateModel(
            name='ExpHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='獲得EXP')),
                ('reason', models.CharField(max_length=100, verbose_name='獲得理由')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='獲得日時')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exp_histories', to='accounts.workerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('ROOKIE', 'ROOKIE'), ('REGULAR', 'REGULAR'), ('MASTER', 'MASTER')], default='ROOKIE', max_length=20, verbose_name='グレード')),
                ('level', models.IntegerField(default=0, verbose_name='レベル')),
                ('current_exp', models.IntegerField(default=0, verbose_name='現在の経験値')),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='accounts.workerprofile')),
            ],
        ),
    ]
