# Generated by Django 5.2.10 on 2026-01-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_review_is_good_exphistory_workermembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='identity_document1',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/identity/', verbose_name='本人確認書類1'),
        ),
    ]
