# Generated by Django 5.2.10 on 2026-01-30 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_workerprofile_identity_document1'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='occupation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='現在の職業'),
        ),
    ]
