# Generated by Django 5.2.10 on 2026-01-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_workerprofile_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='緊急連絡先電話番号'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='emergency_relation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='緊急連絡先続柄'),
        ),
    ]
