# Generated by Django 5.2.10 on 2026-02-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_workerprofile_emergency_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='suspension_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='利用停止終了日時'),
        ),
    ]
