# Generated by Django 5.2.10 on 2026-02-03 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_workerprofile_suspension_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenaltyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(verbose_name='ポイント')),
                ('total_points', models.IntegerField(verbose_name='合計ポイント')),
                ('reason', models.CharField(max_length=200, verbose_name='理由')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, verbose_name='発生日時')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalty_histories', to='accounts.workerprofile')),
            ],
        ),
    ]
