@startuml 求人の絞り込みをする

actor    ワーカー    as wo1
boundary さがす画面  as sc1
control  表示        as co1
entity   求人        as jb1
boundary 絞り込み画面 as b1
boundary 勤務地選択画面 as wp1
boundary 都道府県選択画面 as pr1
boundary マップ画面       as mp1

co1 -> jb1 : 求人を参照する
jb1 --> co1 

co1 -> sc1 : 求人一覧を表示する

wo1 -> sc1 : ボタンを押下する

alt 「勤務地選択」ボタンを押下した場合
    sc1 -> wp1 : 勤務地選択画面を表示する
    alt 「×」ボタンを押下した場合
        wp1 -> sc1 : 表示する
    else 「変更」ボタンを押下した場合
        wp1 -> pr1 : 表示する
        wo1 -> pr1 : 都道府県を選択し「OK」ボタンを押下する
        pr1 -> wp1 : 表示する

    else 「マップ」ボタンを押下した場合
        wp1 -> mp1 : マップ画面を表示する
        wo1 -> mp1 : 「この付近を検索」ボタンを押下する
        mp1 -> jb1 : 求人を参照する
        jb1 --> co1 
        co1 -> mp1 : 表示する 
    end
        
else 「日付」ボタンを押下した場合
    sc1 -> jb1 : 日付の絞り込みにあった求人を参照する
    jb1 --> co1 
    co1 -> sc1 : 表示する

else 「絞り込み」ボタンを押下した場合
    sc1 -> b1 : 絞り込み画面を表示する
    wo1 -> b1 : ユーザーは絞り込み条件を設定し\n「絞り込み結果を表示」ボタンを押下する
    b1 -> jb1 : 絞り込み条件にあった求人一覧を参照する
    jb1 --> co1
    co1 -> sc1 : 表示する
end

@enduml