@startuml 応募の申し込みをする

' 1
actor ワーカー as wo1
boundary 求人詳細画面 as jd1
control 表示 as co1
entity 求人 as en1
boundary 本人確認書類選択画面 as iv1
boundary 業務確認画面 as bc1
control 処理 as co2
boundary 質問画面 as qu1
control 処理 as co3

entity メール as ml1

boundary 申し込み完了画面 as ac1

' 2
co1 -> en1 : 求人を参照する
en1 --> co1 

co1 -> jd1 : 求人詳細画面を表示

alt 求人が締切済みの場合
        co1 -> jd1 : システムは「この仕事に申し込む」ボタンを\n「締切済み」ボタンに変更する

    else ペナルティが溜まっている場合
        co1 -> jd1 : システムは「この仕事に申し込む」ボタンを\n「現在申し込みができません」ボタンに変更する

    else 店舗での収入が上限に達している場合
        co1 -> jd1 : システムは「この仕事に申し込む」ボタンを\n「現在申し込みができません」ボタンに変更する

    alt ユーザーが本人確認登録をしていない場合
        co1 -> jd1 : システムは「この仕事に申し込む」ボタンを\n「本人確認に進む」ボタンに変更する
        wo1 -> jd1 : 「本人確認に進む」ボタンを押下する
        jd1 -> iv1 : 表示する:method_GET()
        wo1 -> iv1 : 「本人確認」ボタンを押下する

    else ユーザーが本人確認登録をしている場合
        wo1 -> jd1 : 「この仕事に申し込む」ボタンを押下する
        jd1 -> bc1 : 表示する:method_GET()
        wo1 -> bc1 : 「同意して申し込みを確定」ボタンを押下する
        bc1 -> co2 : 起動:method_POST()

        alt 質問項目がない場合
            co2 -> ml1 : 申し込みを送信する
            co2 <-- ml1
            co2 -> ac1 : 表示する
        
        else 質問項目がある場合
            bc1 -> qu1 : 表示する:method_GET()
            wo1 -> qu1 : 質問に回答し「送信」ボタンを押下する
            qu1 -> co3 : 起動:method_POST()

            alt 未入力箇所がある場合
                co3 -> qu1 : 「回答していない質問があります」\nと表示する
            else (全て入力済みの場合)
                co3 -> ml1 : メールを送信する()
                co3 <-- ml1
                co3 -> ac1 : 表示する
            end
        end
    end
end

@enduml